# action.yml
name: test action
description: test action
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
