# action.yml
name: test action
description: test action
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repository }}
    # - ${{ vars.hej }} # does not work to access vars from here
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
