name: Test action
on:
  push:
    branches: [main]

jobs:
  test-action:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - run: echo ${{ vars.hej }}
      - uses: ./
